CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration integer NOT NULL CHECK (duration > 0),
    rating_id BIGINT REFERENCES ratings
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) NOT NULL,
    login varchar(30) NOT NULL CHECK (login <> '' AND login NOT LIKE '% %'),
    name varchar(30),
    birthday date CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id BIGINT REFERENCES films,
    user_id BIGINT REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id BIGINT REFERENCES films,
    genre_id BIGINT REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id    BIGINT REFERENCES users,
    friend_id  BIGINT REFERENCES users,
    status     VARCHAR(20) NOT NULL DEFAULT 'ACCEPTED',
    PRIMARY KEY (user_id, friend_id)
);
