CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration integer NOT NULL CHECK (duration > 0),
    rating_id INTEGER REFERENCES ratings
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) NOT NULL,
    login varchar(30) NOT NULL CHECK (login <> '' AND login NOT LIKE '% %'),
    name varchar(30),
    birthday date CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id INTEGER REFERENCES films,
    user_id INTEGER REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films,
    genre_id INTEGER REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id    INTEGER REFERENCES users,
    friend_id  INTEGER REFERENCES users,
    status     VARCHAR(20) NOT NULL DEFAULT 'pending',
    PRIMARY KEY (user_id, friend_id)
);
